name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Grant execute permission for Maven Wrapper
        run: chmod +x mvnw

      - name: Build and run tests
        run: ./mvnw clean verify

      - name: Generate JaCoCo coverage report
        run: ./mvnw jacoco:report

      - name: SonarCloud Scan
        run: ./mvnw sonar:sonar -Dsonar.projectKey=NguyenHuyHoang20225845_spring-petclinic -Dsonar.organization=NguyenHuyHoang20225845 -Dsonar.host.url=https://sonarcloud.io

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
